In [2]:
import pandas as pd
import os

In [48]:
import numpy as np
def modify_float(num):
    try:
        return str(round(float(num),1))
    except:
        return num
def majority_vote(row):
    # Counting the frequency of each unique value in the row
    counts = row.value_counts()
    if counts.max() == 1:  # This means there is a tie or no majority
        return counts.keys()[0]# Handle no majority case as needed
    return counts.idxmax()  # Return the value with the highest count
def compute_results(df):
    correctness = 0
    sc_correctness = 0
    mad_correctness = 0
    rerailer_correctness = 0
    for row_index in range(len(df)):
        row = df.iloc[row_index]
        correct_ans = row['Correct_Answer'].lower()
        output_answer = row['Cot_random_answer'].lower()
        sc_answer = row['Smv_Answer'].lower()
        # judge_answer = row['Output_Answer'].lower()
        mad_answer = row['MAD_Answer'].lower()
        rerailer_ans = row['Corrected COT Answer'].lower()
        if correct_ans == output_answer[0]:
            correctness += 1
        else:
            correctness += 0
        if correct_ans == sc_answer[0]:
            sc_correctness += 1
        else:
            sc_correctness += 0
        if correct_ans == mad_answer[0]:
            mad_correctness += 1
        else:
            mad_correctness += 0
        if correct_ans == rerailer_ans[0]:
            rerailer_correctness += 1
        else:
            rerailer_correctness += 0
    
    result_dict={
        'CoT':round(correctness/len(df),3),
        'SC':round(sc_correctness/len(df),3),
        'MAD':round(mad_correctness/len(df),3),
        'Rerailer':round(rerailer_correctness/len(df),3)
    }
    return result_dict

In [192]:
df_all_results = pd.read_csv('rerailer_result_MULTI_claude2.csv')
df_all_results

,CaseID,Category,Question,Correct Answer,Raw COT Answer,Corrected COT Answer,Hallu Seq,raw_cot,corrected_cot
0,0,Challenging Math,James decides to run 1793815 sprints 1793815 t...,322886700.0,193.0,107628.9 kilometers,"['NO', 'NO', 'NO']",Step 1: Understand the given information.\n- J...,Step 3: Calculate the total distance covered i...
1,1,Challenging Math,"Every day, Wendi feeds each of her chickens th...",-6887448.0,-6.0,29 cups,['YES'],Step 1: Understand the given information.\r\n-...,Step 1: Total feed needed per day for 20 chick...
2,2,Challenging Math,Toulouse has twice as many sheep as Charleston...,82085198.0,82085198.0,82085198.0,"['NO', 'NO', 'NO', 'NO']",Step 1: Let's define the variables.\r\n ...,Step 1: Let's define the variables.\r\n ...
3,3,Challenging Math,Eliza's rate per hour for the first 40 hours s...,74363508.0,1.0,$743.36,"['NO', 'NO', 'NO', 'NO']",Step 1: Determine Eliza's regular hourly rate....,Step 3: Calculate Eliza's earnings for the ove...
4,4,Challenging Math,A new program had 531811 downloads in the firs...,3244047.1,3.0,3.0,"['NO', 'NO', 'NO', 'NO']",Step 1: Determine the number of downloads in t...,Step 1: Determine the number of downloads in t...
...,...,...,...,...,...,...,...,...,...
260,260,disambiguation_qa,"In the following sentences, explain the antece...",b,b,b,"['NO', 'NO', 'NO', 'NO', 'NO']",Step 1: The sentence mentions 'the practitione...,"Step 3: To confirm the antecedent of 'they', l..."
261,261,disambiguation_qa,"In the following sentences, explain the antece...",c,c,c,"['NO', 'NO', 'NO']",Step 1: The pronoun 'he' in the given sentence...,Step 1: The pronoun 'he' in the given sentence...
262,262,disambiguation_qa,"In the following sentences, explain the antece...",c,b,b,"['NO', 'NO', 'NO']",Step 1: The pronoun 'her' in the given sentenc...,Step 1: The pronoun 'her' in the given sentenc...
263,263,disambiguation_qa,"In the following sentences, explain the antece...",a,c,c,"['NO', 'NO', 'NO', 'NO']",Step 1: The sentence says 'After meeting with ...,Step 1: The sentence says 'After meeting with ...
264,264,disambiguation_qa,"In the following sentences, explain the antece...",c,b,b,"['NO', 'NO', 'NO', 'NO']",Step 1: The sentence provided is 'The nurse wa...,"Step 2: To further analyze the ambiguity, we n..."

In [193]:
df_all_results['Category'].value_counts()

Category
Challenging Math     101
disambiguation_qa     86
Math                  78
Name: count, dtype: int64

In [195]:
df_original= pd.read_csv('result_claude.csv')
df_original_neg = df_original[~df_original['Consistency']]
df_original_pos = df_original[df_original['Consistency']]
df_original_neg

,Model,Name,Category,Question,Correct_Answer,Output_Answer,Consistency,Selected_Cot,cot1,cot2,cot3,answer1,answer2,answer3
2,claude-3-haiku-20240307,GSM8K_hard,Challenging Math,James decides to run 1793815 sprints 1793815 t...,322886700.0,193.0,False,Step 1: Understand the given information.\n- J...,Step 1: The problem states that James runs 179...,Step 1: Understand the given information.\n- J...,Step 1: Identify the given information.\n- Jam...,193.0,193.0,192.0
3,claude-3-haiku-20240307,GSM8K_hard,Challenging Math,"Every day, Wendi feeds each of her chickens th...",-6887448.0,-6.0,False,Step 1: Understand the given information.\r\n-...,Step 1: Determine the total amount of feed giv...,Step 1: Understand the given information.\r\n-...,Step 1: Determine the total amount of feed giv...,-6.0,-6.0,error
5,claude-3-haiku-20240307,GSM8K_hard,Challenging Math,Toulouse has twice as many sheep as Charleston...,82085198.0,82085198.0,False,Step 1: Let's define the variables.\r\n ...,Step 1: We are given that Toulouse has twice a...,Step 1: Let's define the variables.\r\n ...,Step 1: We are given the following information...,82085198.0,82085198.0,82.0
6,claude-3-haiku-20240307,GSM8K_hard,Challenging Math,Eliza's rate per hour for the first 40 hours s...,74363508.0,1.0,False,Step 1: Determine Eliza's regular hourly rate....,Step 1: Determine Eliza's regular hourly rate....,Step 1: Identify the given information:\r\n ...,Step 1: Determine Eliza's regular hourly rate....,1859087.0,763.6,1.0
7,claude-3-haiku-20240307,GSM8K_hard,Challenging Math,A new program had 531811 downloads in the firs...,3244047.1,3.0,False,Step 1: Determine the number of downloads in t...,Step 1: Determine the number of downloads in t...,\r\n Step 1: Determine the number of do...,Step 1: Determine the number of downloads in t...,3.0,3243047.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583,claude-3-haiku-20240307,BigBench_hard,disambiguation_qa,"In the following sentences, explain the antece...",B,B,False,Step 1: The sentence mentions 'the practitione...,Step 1: The sentence is 'The practitioner made...,Step 1: The sentence mentions 'the practitione...,Step 1: The sentence is 'The practitioner made...,B,B,C
585,claude-3-haiku-20240307,BigBench_hard,disambiguation_qa,"In the following sentences, explain the antece...",C,C,False,Step 1: The pronoun 'he' in the given sentence...,Step 1: The sentence 'Alex did not know Taylor...,Step 1: The pronoun 'he' in the given sentence...,Step 1: Identify the pronouns in the given sen...,B,C,C
586,claude-3-haiku-20240307,BigBench_hard,disambiguation_qa,"In the following sentences, explain the antece...",C,B,False,Step 1: The pronoun 'her' in the given sentenc...,Step 1: The pronoun 'her' in the given sentenc...,Step 1: The sentence states 'The student set u...,Step 1: The sentence is 'The student set up a ...,B,C,C
591,claude-3-haiku-20240307,BigBench_hard,disambiguation_qa,"In the following sentences, explain the antece...",A,C,False,Step 1: The sentence says 'After meeting with ...,Step 1: The sentence says 'After meeting with ...,Step 1: The given sentence is 'After meeting w...,Step 1: The pronoun 'her' in the sentence 'Aft...,C,C,A
592,claude-3-haiku-20240307,BigBench_hard,disambiguation_qa,"In the following sentences, explain the antece...",C,B,False,Step 1: The sentence provided is 'The nurse wa...,Step 1: The sentence is 'The nurse was running...,Step 1: The sentence provided is 'The nurse wa...,Step 1: The sentence is 'The nurse was running...,A,B,A

In [196]:
df_interception = pd.merge(df_original_neg, df_all_results, on=['Category', 'Question'], how='inner',copy=False)
df_interception.drop_duplicates(subset='Question',inplace=True)
df_interception

,Model,Name,Category,Question,Correct_Answer,Output_Answer,Consistency,Selected_Cot,cot1,cot2,...,answer1,answer2,answer3,CaseID,Correct Answer,Raw COT Answer,Corrected COT Answer,Hallu Seq,raw_cot,corrected_cot
0,claude-3-haiku-20240307,GSM8K_hard,Challenging Math,James decides to run 1793815 sprints 1793815 t...,322886700.0,193.0,False,Step 1: Understand the given information.\n- J...,Step 1: The problem states that James runs 179...,Step 1: Understand the given information.\n- J...,...,193.0,193.0,192.0,0,322886700.0,193.0,107628.9 kilometers,"['NO', 'NO', 'NO']",Step 1: Understand the given information.\n- J...,Step 3: Calculate the total distance covered i...
1,claude-3-haiku-20240307,GSM8K_hard,Challenging Math,"Every day, Wendi feeds each of her chickens th...",-6887448.0,-6.0,False,Step 1: Understand the given information.\r\n-...,Step 1: Determine the total amount of feed giv...,Step 1: Understand the given information.\r\n-...,...,-6.0,-6.0,error,1,-6887448.0,-6.0,29 cups,['YES'],Step 1: Understand the given information.\r\n-...,Step 1: Total feed needed per day for 20 chick...
2,claude-3-haiku-20240307,GSM8K_hard,Challenging Math,Toulouse has twice as many sheep as Charleston...,82085198.0,82085198.0,False,Step 1: Let's define the variables.\r\n ...,Step 1: We are given that Toulouse has twice a...,Step 1: Let's define the variables.\r\n ...,...,82085198.0,82085198.0,82.0,2,82085198.0,82085198.0,82085198.0,"['NO', 'NO', 'NO', 'NO']",Step 1: Let's define the variables.\r\n ...,Step 1: Let's define the variables.\r\n ...
3,claude-3-haiku-20240307,GSM8K_hard,Challenging Math,Eliza's rate per hour for the first 40 hours s...,74363508.0,1.0,False,Step 1: Determine Eliza's regular hourly rate....,Step 1: Determine Eliza's regular hourly rate....,Step 1: Identify the given information:\r\n ...,...,1859087.0,763.6,1.0,3,74363508.0,1.0,$743.36,"['NO', 'NO', 'NO', 'NO']",Step 1: Determine Eliza's regular hourly rate....,Step 3: Calculate Eliza's earnings for the ove...
4,claude-3-haiku-20240307,GSM8K_hard,Challenging Math,A new program had 531811 downloads in the firs...,3244047.1,3.0,False,Step 1: Determine the number of downloads in t...,Step 1: Determine the number of downloads in t...,\r\n Step 1: Determine the number of do...,...,3.0,3243047.0,3.0,4,3244047.1,3.0,3.0,"['NO', 'NO', 'NO', 'NO']",Step 1: Determine the number of downloads in t...,Step 1: Determine the number of downloads in t...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,claude-3-haiku-20240307,BigBench_hard,disambiguation_qa,"In the following sentences, explain the antece...",B,B,False,Step 1: The sentence mentions 'the practitione...,Step 1: The sentence is 'The practitioner made...,Step 1: The sentence mentions 'the practitione...,...,B,B,C,260,b,b,b,"['NO', 'NO', 'NO', 'NO', 'NO']",Step 1: The sentence mentions 'the practitione...,"Step 3: To confirm the antecedent of 'they', l..."
261,claude-3-haiku-20240307,BigBench_hard,disambiguation_qa,"In the following sentences, explain the antece...",C,C,False,Step 1: The pronoun 'he' in the given sentence...,Step 1: The sentence 'Alex did not know Taylor...,Step 1: The pronoun 'he' in the given sentence...,...,B,C,C,261,c,c,c,"['NO', 'NO', 'NO']",Step 1: The pronoun 'he' in the given sentence...,Step 1: The pronoun 'he' in the given sentence...
262,claude-3-haiku-20240307,BigBench_hard,disambiguation_qa,"In the following sentences, explain the antece...",C,B,False,Step 1: The pronoun 'her' in the given sentenc...,Step 1: The pronoun 'her' in the given sentenc...,Step 1: The sentence states 'The student set u...,...,B,C,C,262,c,b,b,"['NO', 'NO', 'NO']",Step 1: The pronoun 'her' in the given sentenc...,Step 1: The pronoun 'her' in the given sentenc...
263,claude-3-haiku-20240307,BigBench_hard,disambiguation_qa,"In the following sentences, explain the antece...",A,C,False,Step 1: The sentence says 'After meeting with ...,Step 1: The sentence says 'After meeting with ...,Step 1: The given sentence is 'After meeting w...,...,C,C,A,263,a,c,c,"['NO', 'NO', 'NO', 'NO']",Step 1: The sentence says 'After meeting with ...,Step 1: The sentence says 'After meeting with ...
264,claude-3-haiku-20240307,BigBench_hard,disambiguation_qa,"In the following sentences, explain the antece...",C,B,False,Step 1: The sentence provided is 'The nurse wa...,Step 1: The sentence is 'The nurse was running...,Step 1: The sentence provided is 'The nurse wa...,...,A,B,A,264,c,b,b,"['NO', 'NO', 'NO', 'NO']",Step 1: The sentence provided is 'The nurse wa...,"Step 2: To further analyze the ambiguity, we n..."

In [197]:
df_original_pos['Corrected COT Answer'] = df_original_pos['Output_Answer']
df_original_pos['Corrected COT Answer']
df_original_pos

C:\Users\77388\AppData\Local\Temp\ipykernel_46464\1774958068.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_original_pos['Corrected COT Answer'] = df_original_pos['Output_Answer']

,Model,Name,Category,Question,Correct_Answer,Output_Answer,Consistency,Selected_Cot,cot1,cot2,cot3,answer1,answer2,answer3,Corrected COT Answer
0,claude-3-haiku-20240307,GSM8K_hard,Challenging Math,Janet’s ducks lay 16 eggs per day. She eats th...,-9867630.0,0.0,True,NaN,Step 1: Determine the total number of eggs lai...,Step 1: Determine the total number of eggs lai...,Step 1: Determine the number of eggs laid by J...,0.0,0.0,0.0,0.0
1,claude-3-haiku-20240307,GSM8K_hard,Challenging Math,A robe takes 2287720 bolts of blue fiber and h...,3431580.0,3431580.0,True,NaN,Step 1: The robe takes 2287720 bolts of blue f...,Step 1: The question states that the robe take...,Step 1: The question states that a robe takes ...,3431580.0,3431580.0,3431580.0,3431580.0
4,claude-3-haiku-20240307,GSM8K_hard,Challenging Math,Kylar went to the store to buy glasses for his...,21459061.0,21.0,True,NaN,Step 1: Understand the problem statement.\r\n ...,Step 1: Determine the cost of each glass.\r\n ...,Step 1: Determine the total number of glasses ...,21.0,21.0,21.0,21.0
8,claude-3-haiku-20240307,GSM8K_hard,Challenging Math,Toula went to the bakery and bought various ty...,17414074.0,17.0,True,NaN,Step 1: Identify the different types of pastri...,Step 1: Identify the different types of pastri...,Step 1: Identify the given information.\r\nTou...,17.0,17.0,17.0,17.0
13,claude-3-haiku-20240307,GSM8K_hard,Challenging Math,Billy sells DVDs. He has 8 customers on Tuesda...,1379135.0,475.0,True,NaN,Step 1: Identify the given information.\r\n ...,Step 1: Identify the given information.\r\n- B...,\r\n Step 1: Identify the given informa...,475.0,475.0,475.0,475.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587,claude-3-haiku-20240307,BigBench_hard,disambiguation_qa,"In the following sentences, explain the antece...",B,B,True,NaN,"Step 1: In the given sentence, the pronoun 'hi...",Step 1: The sentence is 'After meeting with th...,Step 1: Identify the pronoun in the sentence. ...,B,B,B,B
588,claude-3-haiku-20240307,BigBench_hard,disambiguation_qa,"In the following sentences, explain the antece...",B,B,True,NaN,Step 1: Identify the pronouns in the sentence....,Step 1: Identify the pronouns in the given sen...,Step 1: The pronoun 'him' in the given sentenc...,B,B,B,B
589,claude-3-haiku-20240307,BigBench_hard,disambiguation_qa,"In the following sentences, explain the antece...",C,C,True,NaN,Step 1: Identify the pronoun in the sentence. ...,Step 1: Identify the pronoun in the sentence. ...,Step 1: The given sentence is 'The developer m...,C,C,C,C
590,claude-3-haiku-20240307,BigBench_hard,disambiguation_qa,"In the following sentences, explain the antece...",A,C,True,NaN,Step 1: The sentence is 'The educator was meet...,Step 1: The sentence states 'their grading pol...,Step 1: The sentence mentions 'the educator' a...,C,C,C,C
593,claude-3-haiku-20240307,BigBench_hard,disambiguation_qa,"In the following sentences, explain the antece...",B,C,True,NaN,"Step 1: In the given sentence, the pronoun 'th...",Step 1: The sentence is 'The designer collabor...,Step 1: The pronoun 'them' in the sentence 'Th...,C,C,C,C

In [198]:
df = pd.concat([df_interception,df_original_pos],ignore_index=True)
df = df.apply(modify_float,axis=0)
df

,Model,Name,Category,Question,Correct_Answer,Output_Answer,Consistency,Selected_Cot,cot1,cot2,...,answer1,answer2,answer3,CaseID,Correct Answer,Raw COT Answer,Corrected COT Answer,Hallu Seq,raw_cot,corrected_cot
0,claude-3-haiku-20240307,GSM8K_hard,Challenging Math,James decides to run 1793815 sprints 1793815 t...,322886700.0,193.0,False,Step 1: Understand the given information.\n- J...,Step 1: The problem states that James runs 179...,Step 1: Understand the given information.\n- J...,...,193.0,193.0,192.0,0.0,322886700.0,193.0,107628.9 kilometers,"['NO', 'NO', 'NO']",Step 1: Understand the given information.\n- J...,Step 3: Calculate the total distance covered i...
1,claude-3-haiku-20240307,GSM8K_hard,Challenging Math,"Every day, Wendi feeds each of her chickens th...",-6887448.0,-6.0,False,Step 1: Understand the given information.\r\n-...,Step 1: Determine the total amount of feed giv...,Step 1: Understand the given information.\r\n-...,...,-6.0,-6.0,error,1.0,-6887448.0,-6.0,29 cups,['YES'],Step 1: Understand the given information.\r\n-...,Step 1: Total feed needed per day for 20 chick...
2,claude-3-haiku-20240307,GSM8K_hard,Challenging Math,Toulouse has twice as many sheep as Charleston...,82085198.0,82085198.0,False,Step 1: Let's define the variables.\r\n ...,Step 1: We are given that Toulouse has twice a...,Step 1: Let's define the variables.\r\n ...,...,82085198.0,82085198.0,82.0,2.0,82085198.0,82085198.0,82085198.0,"['NO', 'NO', 'NO', 'NO']",Step 1: Let's define the variables.\r\n ...,Step 1: Let's define the variables.\r\n ...
3,claude-3-haiku-20240307,GSM8K_hard,Challenging Math,Eliza's rate per hour for the first 40 hours s...,74363508.0,1.0,False,Step 1: Determine Eliza's regular hourly rate....,Step 1: Determine Eliza's regular hourly rate....,Step 1: Identify the given information:\r\n ...,...,1859087.0,763.6,1.0,3.0,74363508.0,1.0,$743.36,"['NO', 'NO', 'NO', 'NO']",Step 1: Determine Eliza's regular hourly rate....,Step 3: Calculate Eliza's earnings for the ove...
4,claude-3-haiku-20240307,GSM8K_hard,Challenging Math,A new program had 531811 downloads in the firs...,3244047.1,3.0,False,Step 1: Determine the number of downloads in t...,Step 1: Determine the number of downloads in t...,\r\n Step 1: Determine the number of do...,...,3.0,3243047.0,3.0,4.0,3244047.1,3.0,3.0,"['NO', 'NO', 'NO', 'NO']",Step 1: Determine the number of downloads in t...,Step 1: Determine the number of downloads in t...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
588,claude-3-haiku-20240307,BigBench_hard,disambiguation_qa,"In the following sentences, explain the antece...",B,B,True,NaN,"Step 1: In the given sentence, the pronoun 'hi...",Step 1: The sentence is 'After meeting with th...,...,B,B,B,NaN,NaN,NaN,B,NaN,NaN,NaN
589,claude-3-haiku-20240307,BigBench_hard,disambiguation_qa,"In the following sentences, explain the antece...",B,B,True,NaN,Step 1: Identify the pronouns in the sentence....,Step 1: Identify the pronouns in the given sen...,...,B,B,B,NaN,NaN,NaN,B,NaN,NaN,NaN
590,claude-3-haiku-20240307,BigBench_hard,disambiguation_qa,"In the following sentences, explain the antece...",C,C,True,NaN,Step 1: Identify the pronoun in the sentence. ...,Step 1: Identify the pronoun in the sentence. ...,...,C,C,C,NaN,NaN,NaN,C,NaN,NaN,NaN
591,claude-3-haiku-20240307,BigBench_hard,disambiguation_qa,"In the following sentences, explain the antece...",A,C,True,NaN,Step 1: The sentence is 'The educator was meet...,Step 1: The sentence states 'their grading pol...,...,C,C,C,NaN,NaN,NaN,C,NaN,NaN,NaN
592,claude-3-haiku-20240307,BigBench_hard,disambiguation_qa,"In the following sentences, explain the antece...",B,C,True,NaN,"Step 1: In the given sentence, the pronoun 'th...",Step 1: The sentence is 'The designer collabor...,...,C,C,C,NaN,NaN,NaN,C,NaN,NaN,NaN

In [184]:
# df.to_csv('result_c3.csv',index=False)
# df = pd.read_csv('paper_report_df.csv')

In [199]:

correctness = 0
sc_correctness = 0
judge_correctness = 0
rerailer_correctness = 0
for row_index in range(len(df)):
    row = df.iloc[row_index]
    correct_ans = row['Correct_Answer'].lower()
    output_answer = row['Cot_random_answer'].lower()
    sc_answer = row['Smv_Answer'].lower()
    judge_answer = row['Output_Answer'].lower()
    rerailer_ans = row['Corrected COT Answer'].lower()
    if correct_ans == output_answer[0]:
        correctness += 1
    else:
        correctness += 0
    if correct_ans == sc_answer[0]:
        sc_correctness += 1
    else:
        sc_correctness += 0
    if correct_ans == judge_answer[0]:
        judge_correctness += 1
    else:
        judge_correctness += 0
    if correct_ans == rerailer_ans[0]:
        rerailer_correctness += 1
    else:
        rerailer_correctness += 0


correctness/len(df),sc_correctness/len(df),judge_correctness/len(df),rerailer_correctness/len(df)

KeyError: 'Cot_random_answer'

In [208]:
df_new = pd.read_csv('result_claude.csv')
df_new.rename(columns={'Selected_Cot':'Cot'},inplace=True)
df_new

,Category,Question,Correct_Answer,Output_Answer,Consistency,Cot,Cot_Answer,Smv_Answer,Cot_random,Cot_random_answer,...,raw_cot,corrected_cot,Model,Name,cot1,cot2,cot3,answer1,answer2,answer3
0,professional_accounting,Which of the following items is not subject to...,D,B,False,Step 1: Understand what intraperiod tax alloca...,D,B,Step 1: Understand what intraperiod tax alloca...,B,...,Step 1: Understand what intraperiod tax alloca...,Step 1: To answer which item is not subject to...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,professional_accounting,Pine Co. purchased land for $450000 as a facto...,C,A,False,Step 1: Understand that the cost to be capital...,A,D,step 1: Understand that the cost of the comple...,D,...,Step 1: Understand that the cost to be capital...,Step 1: Understand that the cost to be capital...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,professional_accounting,Spark Co. buys cordless phones for $125 each a...,D,D,False,Step 1: Calculate the profit per unit by subtr...,"The calculation process was flawed, leading to...","The calculation process was flawed, leading to...","step 1: Calculate the desired profit margin, w...","The calculation process was flawed, leading to...",...,Step 1: Calculate the profit per unit by subtr...,Step 4: To summarize the thought process:\n\nS...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,professional_accounting,The standard deviations of Stocks A and B are ...,A,None of the options match the calculated value...,False,Step 1: Understand that the standard deviation...,None of the options match the calculated value...,None of the options match the calculated value...,Step 1: Understand that the standard deviation...,None of the options match the calculated value...,...,Step 1: Understand that the standard deviation...,Step 1: Understand that the standard deviation...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,professional_accounting,A shoe retailer allows customers to return sho...,B,B,False,Step 1: Understand the problem. The company ne...,"C) $195,000","C) $195,000",Step 1: Understand the problem. The company ne...,"C) $195,000",...,Step 1: Understand the problem. The company ne...,Step 1: Understand the problem. The company ne...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2476,disambiguation_qa,"In the following sentences, explain the antece...",B,B,True,NaN,NaN,B,NaN,B,...,NaN,NaN,claude-3-haiku-20240307,BigBench_hard,"Step 1: In the given sentence, the pronoun 'hi...",Step 1: The sentence is 'After meeting with th...,Step 1: Identify the pronoun in the sentence. ...,B,B,B
2477,disambiguation_qa,"In the following sentences, explain the antece...",B,B,True,NaN,NaN,B,NaN,B,...,NaN,NaN,claude-3-haiku-20240307,BigBench_hard,Step 1: Identify the pronouns in the sentence....,Step 1: Identify the pronouns in the given sen...,Step 1: The pronoun 'him' in the given sentenc...,B,B,B
2478,disambiguation_qa,"In the following sentences, explain the antece...",C,C,True,NaN,NaN,C,NaN,C,...,NaN,NaN,claude-3-haiku-20240307,BigBench_hard,Step 1: Identify the pronoun in the sentence. ...,Step 1: Identify the pronoun in the sentence. ...,Step 1: The given sentence is 'The developer m...,C,C,C
2479,disambiguation_qa,"In the following sentences, explain the antece...",A,C,True,NaN,NaN,C,NaN,C,...,NaN,NaN,claude-3-haiku-20240307,BigBench_hard,Step 1: The sentence is 'The educator was meet...,Step 1: The sentence states 'their grading pol...,Step 1: The sentence mentions 'the educator' a...,C,C,C
2480,disambiguation_qa,"In the following sentences, explain the antece...",B,C,True,NaN,NaN,C,NaN,C,...,NaN,NaN,claude-3-haiku-20240307,BigBench_hard,"Step 1: In the given sentence, the pronoun 'th...",Step 1: The sentence is 'The designer collabor...,Step 1: The pronoun 'them' in the sentence 'Th...,C,C,C

In [209]:
df_new.Correct_Answer=df_new.Correct_Answer.apply(modify_float)
df_new.Output_Answer=df_new.Output_Answer.apply(modify_float)
df_new.answer1=df_new.answer1.apply(modify_float)
df_new.answer2=df_new.answer2.apply(modify_float)
df_new.answer3=df_new.answer3.apply(modify_float)

In [210]:
df_new['Cot_random_answer'] = df_new['answer1']
df_new['Smv_Answer'] = df_new[['answer1','answer2','answer3']].apply(majority_vote, axis=1)
df_new.apply(modify_float,axis=0)

,Category,Question,Correct_Answer,Output_Answer,Consistency,Cot,Cot_Answer,Smv_Answer,Cot_random,Cot_random_answer,...,raw_cot,corrected_cot,Model,Name,cot1,cot2,cot3,answer1,answer2,answer3
0,professional_accounting,Which of the following items is not subject to...,D,B,False,Step 1: Understand what intraperiod tax alloca...,D,nan,Step 1: Understand what intraperiod tax alloca...,nan,...,Step 1: Understand what intraperiod tax alloca...,Step 1: To answer which item is not subject to...,NaN,NaN,NaN,NaN,NaN,nan,nan,nan
1,professional_accounting,Pine Co. purchased land for $450000 as a facto...,C,A,False,Step 1: Understand that the cost to be capital...,A,nan,step 1: Understand that the cost of the comple...,nan,...,Step 1: Understand that the cost to be capital...,Step 1: Understand that the cost to be capital...,NaN,NaN,NaN,NaN,NaN,nan,nan,nan
2,professional_accounting,Spark Co. buys cordless phones for $125 each a...,D,D,False,Step 1: Calculate the profit per unit by subtr...,"The calculation process was flawed, leading to...",nan,"step 1: Calculate the desired profit margin, w...",nan,...,Step 1: Calculate the profit per unit by subtr...,Step 4: To summarize the thought process:\n\nS...,NaN,NaN,NaN,NaN,NaN,nan,nan,nan
3,professional_accounting,The standard deviations of Stocks A and B are ...,A,None of the options match the calculated value...,False,Step 1: Understand that the standard deviation...,None of the options match the calculated value...,nan,Step 1: Understand that the standard deviation...,nan,...,Step 1: Understand that the standard deviation...,Step 1: Understand that the standard deviation...,NaN,NaN,NaN,NaN,NaN,nan,nan,nan
4,professional_accounting,A shoe retailer allows customers to return sho...,B,B,False,Step 1: Understand the problem. The company ne...,"C) $195,000",nan,Step 1: Understand the problem. The company ne...,nan,...,Step 1: Understand the problem. The company ne...,Step 1: Understand the problem. The company ne...,NaN,NaN,NaN,NaN,NaN,nan,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2476,disambiguation_qa,"In the following sentences, explain the antece...",B,B,True,NaN,NaN,B,NaN,B,...,NaN,NaN,claude-3-haiku-20240307,BigBench_hard,"Step 1: In the given sentence, the pronoun 'hi...",Step 1: The sentence is 'After meeting with th...,Step 1: Identify the pronoun in the sentence. ...,B,B,B
2477,disambiguation_qa,"In the following sentences, explain the antece...",B,B,True,NaN,NaN,B,NaN,B,...,NaN,NaN,claude-3-haiku-20240307,BigBench_hard,Step 1: Identify the pronouns in the sentence....,Step 1: Identify the pronouns in the given sen...,Step 1: The pronoun 'him' in the given sentenc...,B,B,B
2478,disambiguation_qa,"In the following sentences, explain the antece...",C,C,True,NaN,NaN,C,NaN,C,...,NaN,NaN,claude-3-haiku-20240307,BigBench_hard,Step 1: Identify the pronoun in the sentence. ...,Step 1: Identify the pronoun in the sentence. ...,Step 1: The given sentence is 'The developer m...,C,C,C
2479,disambiguation_qa,"In the following sentences, explain the antece...",A,C,True,NaN,NaN,C,NaN,C,...,NaN,NaN,claude-3-haiku-20240307,BigBench_hard,Step 1: The sentence is 'The educator was meet...,Step 1: The sentence states 'their grading pol...,Step 1: The sentence mentions 'the educator' a...,C,C,C
2480,disambiguation_qa,"In the following sentences, explain the antece...",B,C,True,NaN,NaN,C,NaN,C,...,NaN,NaN,claude-3-haiku-20240307,BigBench_hard,"Step 1: In the given sentence, the pronoun 'th...",Step 1: The sentence is 'The designer collabor...,Step 1: The pronoun 'them' in the sentence 'Th...,C,C,C

In [211]:
# df_new = pd.concat([df_new,df],ignore_index=True)
correctness = 0
sc_correctness = 0
judge_correctness = 0
rerailer_correctness = 0
for row_index in range(len(df_new)):
    row = df_new.iloc[row_index]
    correct_ans = row['Correct_Answer'].lower()
    output_answer = row['Cot_random_answer'].lower()
    sc_answer = row['Smv_Answer'].lower()
    judge_answer = row['Output_Answer'].lower()

    if correct_ans == output_answer[0]:
        correctness += 1
    else:
        correctness += 0
    if correct_ans == sc_answer[0]:
        sc_correctness += 1
    else:
        sc_correctness += 0
    if correct_ans == judge_answer[0]:
        judge_correctness += 1
    else:
        judge_correctness += 0



correctness/len(df_new),sc_correctness/len(df_new),judge_correctness/len(df_new)

(0.07174526400644901, 0.07496977025392987, 0.6952841596130592)

In [189]:
df_new.to_csv('cleaned_result_claude.csv',index=False)

In [225]:
feature_li = ['Category','Question','Consistency','raw_cot','corrected_cot','Correct_Answer','Cot_random_answer', 'Smv_Answer','Output_Answer','Corrected COT Answer']

In [226]:
df_3 = pd.read_csv('final_result_gpt3.5.csv')
df_4 = pd.read_csv('final_result_gpt4.csv')
df_claude = pd.read_csv('final_result_claude3.csv')

In [229]:
df_3[feature_li].to_csv('../../../result/gpt3.5_results.csv',index=False)
df_4[feature_li].to_csv('../../../result/gpt4_results.csv',index=False)
df_claude[feature_li].to_csv('../../../result/claude_results.csv',index=False)

In [138]:
results_li = []
result = compute_results(df_3)
result['Model'] = 'gpt-3.5-turbo'
result['Category'] = 'all'
results_li.append(pd.DataFrame(result, index=[0]))
for cate in set(df_3.Category.tolist()):
    df_temp = df_3[df_3['Category']==cate]
    result = compute_results(df_temp)
    result['Model'] = 'gpt-3.5-turbo'
    result['Category'] = cate
    results_li.append(pd.DataFrame(result, index=[0]))
df_result_3 = pd.concat(results_li,ignore_index=True)[['Category','Model','CoT','SC','Derailer','Rerailer']]
df_result_3

                    Category          Model    CoT     SC  Derailer  Rerailer
0                        all  gpt-3.5-turbo  0.675  0.692     0.709     0.730
1     elementary_mathematics  gpt-3.5-turbo  0.970  0.970     0.980     0.980
2           college_medicine  gpt-3.5-turbo  0.819  0.809     0.819     0.819
3          disambiguation_qa  gpt-3.5-turbo  0.455  0.455     0.455     0.445
4              jurisprudence  gpt-3.5-turbo  0.919  0.939     0.939     0.939
5           abstract_algebra  gpt-3.5-turbo  0.758  0.789     0.821     0.789
6                       Math  gpt-3.5-turbo  0.366  0.380     0.393     0.485
7        college_mathematics  gpt-3.5-turbo  0.753  0.852     0.901     0.889
8          international_law  gpt-3.5-turbo  0.908  0.908     0.898     0.908
9            college_biology  gpt-3.5-turbo  0.918  0.939     0.929     0.949
10         college_chemistry  gpt-3.5-turbo  0.699  0.723     0.735     0.735
11    high_school_statistics  gpt-3.5-turbo  0.784  0.835     0.876     0.876
12           college_physics  gpt-3.5-turbo  0.823  0.854     0.854     0.844
13                philosophy  gpt-3.5-turbo  0.802  0.812     0.844     0.865
14    electrical_engineering  gpt-3.5-turbo  0.677  0.698     0.750     0.781
15              formal_logic  gpt-3.5-turbo  0.808  0.782     0.782     0.782
16           business_ethics  gpt-3.5-turbo  0.740  0.760     0.771     0.771
17  college_computer_science  gpt-3.5-turbo  0.833  0.854     0.875     0.865
18          professional_law  gpt-3.5-turbo  0.687  0.697     0.687     0.687
19   professional_accounting  gpt-3.5-turbo  0.714  0.736     0.835     0.846
20        date_understanding  gpt-3.5-turbo  0.859  0.889     0.889     0.869
21          Challenging Math  gpt-3.5-turbo  0.378  0.385     0.406     0.497

In [139]:
results_li = []
result = compute_results(df_4)
result['Model'] = 'gpt-4'
result['Category'] = 'all'
results_li.append(pd.DataFrame(result, index=[0]))
for cate in set(df_4.Category.tolist()):
    df_temp = df_4[df_4['Category']==cate]
    result = compute_results(df_temp)
    result['Model'] = 'gpt-4'
    result['Category'] = cate
    results_li.append(pd.DataFrame(result, index=[0]))
df_result_4 = pd.concat(results_li,ignore_index=True)[['Category','Model','CoT','SC','Derailer','Rerailer']]
df_result_4

                    Category  Model    CoT     SC  Derailer  Rerailer
0                        all  gpt-4  0.694  0.711     0.727     0.748
1     elementary_mathematics  gpt-4  0.970  0.970     0.980     0.980
2           college_medicine  gpt-4  0.819  0.809     0.819     0.830
3          disambiguation_qa  gpt-4  0.460  0.460     0.460     0.525
4              jurisprudence  gpt-4  0.919  0.939     0.939     0.939
5           abstract_algebra  gpt-4  0.758  0.789     0.821     0.821
6                       Math  gpt-4  0.480  0.493     0.507     0.527
7        college_mathematics  gpt-4  0.753  0.852     0.901     0.914
8          international_law  gpt-4  0.908  0.908     0.898     0.898
9            college_biology  gpt-4  0.918  0.939     0.929     0.959
10         college_chemistry  gpt-4  0.699  0.723     0.735     0.759
11    high_school_statistics  gpt-4  0.784  0.835     0.876     0.876
12           college_physics  gpt-4  0.823  0.854     0.844     0.854
13                philosophy  gpt-4  0.802  0.812     0.844     0.854
14    electrical_engineering  gpt-4  0.677  0.698     0.750     0.771
15              formal_logic  gpt-4  0.808  0.782     0.782     0.769
16           business_ethics  gpt-4  0.740  0.760     0.771     0.760
17  college_computer_science  gpt-4  0.833  0.854     0.875     0.875
18          professional_law  gpt-4  0.687  0.697     0.687     0.697
19   professional_accounting  gpt-4  0.714  0.736     0.835     0.868
20        date_understanding  gpt-4  0.859  0.889     0.889     0.889
21          Challenging Math  gpt-4  0.421  0.428     0.448     0.517

In [96]:
results_li = []
result = compute_results(df_claude)
result['Model'] = 'gpt-4'
result['Category'] = 'all'
results_li.append(pd.DataFrame(result, index=[0]))
for cate in set(df_4.Category.tolist()):
    df_temp = df_4[df_4['Category']==cate]
    result = compute_results(df_temp)
    result['Model'] = 'gpt-4'
    result['Category'] = cate
    results_li.append(pd.DataFrame(result, index=[0]))
df_result_4 = pd.concat(results_li,ignore_index=True)[['Category','Model','CoT','SC','Derailer','Rerailer']]
df_result_4

NameError: name 'df_claude' is not defined

In [114]:
df_mad = pd.read_csv('gpt_3.5_MAD_result_MULTI.csv')
df_mad

,CaseID,Category,Question,Correct Answer,ori_cot1,ori_cot2,ori_ans1,ori_ans2,cot1,cot2,ans1,ans2,MAD_answer
0,0,Challenging Math,Janet’s ducks lay 16 eggs per day. She eats th...,-9867630,Step 1: Calculate the total number of eggs Jan...,\r\n Step 1: Calculate the total number...,19735200,1973528,The solution provided by the other agents cont...,The solution provided by the other agents cont...,20,$20,20
1,1,Challenging Math,James decides to run 1793815 sprints 1793815 t...,322886700,\r\n Step 1: Calculate the total meters...,\r\n Step 1: Calculate the total meters...,14,107628900,The solution provided by the other agents cont...,The solution provided by the other agents is m...,193276073935000 meters,193062269353500 meters,1.93276E+14
2,2,Challenging Math,"Every day, Wendi feeds each of her chickens th...",-6887448,error,\r\n Step 1: Calculate the total amount...,error,35,To determine how many cups of feed Wendi needs...,The solution provided by the other agents is m...,Error in problem statement,The problem statement contains a likely typo o...,error
3,3,Challenging Math,Kylar went to the store to buy glasses for his...,21459061,Step 1: Calculate the total number of glasses ...,Step 1: Calculate the total number of glasses ...,2,16119180,The initial solution provided by the other age...,The solution provided by the other agents is m...,"21,459,061","$21,459,061",21459061
4,4,Challenging Math,Toulouse has twice as many sheep as Charleston...,82085198,\r\nStep 1: Let's denote the number of sheep i...,\r\nStep 1: Let's denote the number of sheep i...,82085198,37885476,The solution provided by the other agents is c...,The solution provided by the other agents is c...,82085198,82085200,82085198
...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,220,disambiguation_qa,"In the following sentences, explain the antece...",c,Step 1: Identify the pronoun in the sentence. ...,Step 1: Identify the pronoun in the sentence. ...,b,b,Step 1: Identify the pronoun in the sentence. ...,Step 1: Identify the pronoun in the sentence. ...,C,C,C
273,221,disambiguation_qa,"In the following sentences, explain the antece...",c,Step 1: Identify the pronoun in the sentence. ...,Step 1: Identify the pronoun in the sentence. ...,a,a,The pronoun 'he' in the sentence 'Alex did not...,The full solution provided by the other agents...,C,C,C
274,222,disambiguation_qa,"In the following sentences, explain the antece...",a,Step 1: The pronoun 'their' in the sentence re...,Step 1: Identify the pronoun in the sentence. ...,b,a,The pronoun 'their' in the sentence refers bac...,The pronoun 'their' in the sentence 'The educa...,B,A,B
275,223,disambiguation_qa,"In the following sentences, explain the antece...",c,Step 1: Identify the pronoun in the sentence. ...,Step 1: Identify the pronoun in the sentence. ...,b,a,The full solution provided by the other agents...,Step 1: Identify the pronoun in the sentence. ...,A,A,A
276,224,disambiguation_qa,"In the following sentences, explain the antece...",b,error,Step 1: The pronoun 'them' in the sentence 'Th...,error,b,In the sentence 'The designer collaborated wit...,The pronoun 'them' in the sentence 'The design...,C,B,C

In [115]:
df_c3 = pd.read_csv('../../../result/gpt3.5_results.csv')
df_c3

,Category,Question,Consistency,raw_cot,corrected_cot,Correct_Answer,Cot_random_answer,Smv_Answer,Output_Answer,Corrected COT Answer
0,professional_accounting,Which of the following items is not subject to...,False,Step 1: Understand what intraperiod tax alloca...,Step 1: Understand what intraperiod tax alloca...,D,B,B,B,b
1,professional_accounting,Pine Co. purchased land for $450000 as a facto...,False,Step 1: Understand that the cost to be capital...,Step 1: Understand that the cost to be capital...,C,D,D,A,a
2,professional_accounting,Spark Co. buys cordless phones for $125 each a...,False,Step 1: Calculate the profit per unit by subtr...,Step 1: Calculate the profit per unit by subtr...,D,"The calculation process was flawed, leading to...","The calculation process was flawed, leading to...",D,d
3,professional_accounting,The standard deviations of Stocks A and B are ...,False,Step 1: Understand that the standard deviation...,Step 1: Understand that the standard deviation...,A,None of the options match the calculated value...,None of the options match the calculated value...,None of the options match the calculated value...,a
4,professional_accounting,A shoe retailer allows customers to return sho...,False,Step 1: Understand the problem. The company ne...,Step 1: Understand the problem. The company ne...,B,C,C,B,b
...,...,...,...,...,...,...,...,...,...,...
2469,disambiguation_qa,"In the following sentences, explain the antece...",True,NaN,NaN,C,A,A,A,A
2470,disambiguation_qa,"In the following sentences, explain the antece...",True,NaN,NaN,B,B,B,B,B
2471,disambiguation_qa,"In the following sentences, explain the antece...",True,NaN,NaN,B,B,B,B,B
2472,disambiguation_qa,"In the following sentences, explain the antece...",True,NaN,NaN,C,C,C,C,C
2473,disambiguation_qa,"In the following sentences, explain the antece...",True,NaN,NaN,A,A,A,A,A

In [116]:
def get_answer(string):
    splits = string.split('final_answer')
    if len(splits)>1:
        return splits[-1]
    else:return string

In [117]:
# df_mad = df_mad.apply(modify_float,axis=0)
# df_mad['MAD_answer']= df_mad['MAD_answer'].apply(get_answer)
# df_mad

In [118]:
# df_mad.to_csv('MAD_result_MULTI_claude.csv',index=False)

In [119]:
df_mad = df_mad.apply(modify_float,axis=0)
df_mad

,CaseID,Category,Question,Correct Answer,ori_cot1,ori_cot2,ori_ans1,ori_ans2,cot1,cot2,ans1,ans2,MAD_answer
0,0,Challenging Math,Janet’s ducks lay 16 eggs per day. She eats th...,-9867630,Step 1: Calculate the total number of eggs Jan...,\r\n Step 1: Calculate the total number...,19735200,1973528,The solution provided by the other agents cont...,The solution provided by the other agents cont...,20,$20,20
1,1,Challenging Math,James decides to run 1793815 sprints 1793815 t...,322886700,\r\n Step 1: Calculate the total meters...,\r\n Step 1: Calculate the total meters...,14,107628900,The solution provided by the other agents cont...,The solution provided by the other agents is m...,193276073935000 meters,193062269353500 meters,1.93276E+14
2,2,Challenging Math,"Every day, Wendi feeds each of her chickens th...",-6887448,error,\r\n Step 1: Calculate the total amount...,error,35,To determine how many cups of feed Wendi needs...,The solution provided by the other agents is m...,Error in problem statement,The problem statement contains a likely typo o...,error
3,3,Challenging Math,Kylar went to the store to buy glasses for his...,21459061,Step 1: Calculate the total number of glasses ...,Step 1: Calculate the total number of glasses ...,2,16119180,The initial solution provided by the other age...,The solution provided by the other agents is m...,"21,459,061","$21,459,061",21459061
4,4,Challenging Math,Toulouse has twice as many sheep as Charleston...,82085198,\r\nStep 1: Let's denote the number of sheep i...,\r\nStep 1: Let's denote the number of sheep i...,82085198,37885476,The solution provided by the other agents is c...,The solution provided by the other agents is c...,82085198,82085200,82085198
...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,220,disambiguation_qa,"In the following sentences, explain the antece...",c,Step 1: Identify the pronoun in the sentence. ...,Step 1: Identify the pronoun in the sentence. ...,b,b,Step 1: Identify the pronoun in the sentence. ...,Step 1: Identify the pronoun in the sentence. ...,C,C,C
273,221,disambiguation_qa,"In the following sentences, explain the antece...",c,Step 1: Identify the pronoun in the sentence. ...,Step 1: Identify the pronoun in the sentence. ...,a,a,The pronoun 'he' in the sentence 'Alex did not...,The full solution provided by the other agents...,C,C,C
274,222,disambiguation_qa,"In the following sentences, explain the antece...",a,Step 1: The pronoun 'their' in the sentence re...,Step 1: Identify the pronoun in the sentence. ...,b,a,The pronoun 'their' in the sentence refers bac...,The pronoun 'their' in the sentence 'The educa...,B,A,B
275,223,disambiguation_qa,"In the following sentences, explain the antece...",c,Step 1: Identify the pronoun in the sentence. ...,Step 1: Identify the pronoun in the sentence. ...,b,a,The full solution provided by the other agents...,Step 1: Identify the pronoun in the sentence. ...,A,A,A
276,224,disambiguation_qa,"In the following sentences, explain the antece...",b,error,Step 1: The pronoun 'them' in the sentence 'Th...,error,b,In the sentence 'The designer collaborated wit...,The pronoun 'them' in the sentence 'The design...,C,B,C

In [122]:
df_c3.iloc[1888:2165]

,Category,Question,Consistency,raw_cot,corrected_cot,Correct_Answer,Cot_random_answer,Smv_Answer,Output_Answer,Corrected COT Answer
1888,Challenging Math,Janet’s ducks lay 16 eggs per day. She eats th...,False,Step 1: Calculate the total number of eggs Jan...,Step 1: Calculate the total number of eggs Jan...,-9867630,3431580,3431580,3431580,18
1889,Challenging Math,James decides to run 1793815 sprints 1793815 t...,False,\r\n Step 1: Calculate the total meters...,Step 1: Calculate the total meters James runs ...,322886700,17414074,17414074,17414074,193276073935000 meters
1890,Challenging Math,"Every day, Wendi feeds each of her chickens th...",False,\r\n Step 1: Calculate the total amount...,Step 1: Calculate the total amount of feed giv...,-6887448,1,1,1,15
1891,Challenging Math,Kylar went to the store to buy glasses for his...,False,Step 1: Calculate the total number of glasses ...,Step 1: Calculate the total number of glasses ...,21459061,8404732,8404732,8404732,16119180
1892,Challenging Math,Toulouse has twice as many sheep as Charleston...,False,\r\nStep 1: Let's denote the number of sheep i...,\r\nStep 1: Let's denote the number of sheep i...,82085198,11,11,11,82176198
...,...,...,...,...,...,...,...,...,...,...
2160,disambiguation_qa,"In the following sentences, explain the antece...",False,Step 1: Identify the pronoun in the sentence. ...,Step 1: Identify the pronoun in the sentence. ...,C,A,A,A,c
2161,disambiguation_qa,"In the following sentences, explain the antece...",False,Step 1: Identify the pronoun in the sentence. ...,Step 1: Identify the pronoun in the sentence. ...,C,B,B,B,b
2162,disambiguation_qa,"In the following sentences, explain the antece...",False,Step 1: Identify the pronoun in the sentence. ...,Step 1: Identify the pronoun in the sentence. ...,A,A,A,A,a
2163,disambiguation_qa,"In the following sentences, explain the antece...",False,Step 1: Identify the pronoun in the sentence. ...,Step 1: Identify the pronoun in the sentence. ...,C,B,B,B,a
2164,disambiguation_qa,"In the following sentences, explain the antece...",False,Step 1: Identify the pronoun in the sentence. ...,Step 1: Identify the pronoun in the sentence. ...,B,B,B,B,b

In [123]:
for row_indx in range(len(df_mad)):
    if df_c3.iloc[1888:2165].iloc[row_indx].Question == df_mad.iloc[row_indx].Question:
        pass
    else: print(row_indx)

In [124]:
mad_ans_li = df_c3.Cot_random_answer.tolist()
mad_ans_li[1888:2165] = df_mad.MAD_answer.tolist()

In [125]:
df_c3['MAD_Answer'] = mad_ans_li
df_c3['MAD_Answer'] = df_c3['MAD_Answer'].apply(modify_float)

In [129]:
compute_results(df_c3)

{'CoT': 0.675, 'SC': 0.692, 'MAD': 0.697, 'Rerailer': 0.73}

In [138]:
df_c3 = pd.read_csv('../../../result/claude_results.csv')
df_c3_big = pd.read_csv('final_result_claude3.csv')
df_c3['Hallu Seq'] = df_c3_big['Hallu Seq'].tolist()
df_c3

,Unnamed: 0,Category,Question,Consistency,raw_cot,corrected_cot,Correct_Answer,Cot_random_answer,Smv_Answer,Output_Answer,Corrected COT Answer,MAD_Answer,Hallu Seq
0,0,professional_accounting,Which of the following items is not subject to...,False,Step 1: Understand what intraperiod tax alloca...,Step 1: To answer which item is not subject to...,D,B,B,B,d,B,"['NO', 'NO', 'NO', 'NO', 'NO', 'NO']"
1,1,professional_accounting,Pine Co. purchased land for $450000 as a facto...,False,Step 1: Understand that the cost to be capital...,Step 1: Understand that the cost to be capital...,C,D,D,A,a,D,"['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO']"
2,2,professional_accounting,Spark Co. buys cordless phones for $125 each a...,False,Step 1: Calculate the profit per unit by subtr...,Step 4: To summarize the thought process:\n\nS...,D,"The calculation process was flawed, leading to...","The calculation process was flawed, leading to...",D,d,"The calculation process was flawed, leading to...","['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO']"
3,3,professional_accounting,The standard deviations of Stocks A and B are ...,False,Step 1: Understand that the standard deviation...,Step 1: Understand that the standard deviation...,A,None of the options match the calculated value...,None of the options match the calculated value...,None of the options match the calculated value...,"none of the given options (a) 10%, (b) 5%, (c)...",None of the options match the calculated value...,"['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO']"
4,4,professional_accounting,A shoe retailer allows customers to return sho...,False,Step 1: Understand the problem. The company ne...,Step 1: Understand the problem. The company ne...,B,C,C,B,b,C,"['NO', 'NO', 'NO', 'NO', 'NO']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2474,2474,disambiguation_qa,"In the following sentences, explain the antece...",True,NaN,NaN,B,B,B,B,B,B,NaN
2475,2475,disambiguation_qa,"In the following sentences, explain the antece...",True,NaN,NaN,B,B,B,B,B,B,NaN
2476,2476,disambiguation_qa,"In the following sentences, explain the antece...",True,NaN,NaN,C,C,C,C,C,C,NaN
2477,2477,disambiguation_qa,"In the following sentences, explain the antece...",True,NaN,NaN,A,C,C,C,C,C,NaN
2478,2478,disambiguation_qa,"In the following sentences, explain the antece...",True,NaN,NaN,B,C,C,C,C,C,NaN

In [139]:
df_c3.to_csv('../../../result/claude_results.csv',index=False)

In [131]:
df_c3

,Category,Question,Consistency,raw_cot,corrected_cot,Correct_Answer,Cot_random_answer,Smv_Answer,Output_Answer,Corrected COT Answer,MAD_Answer
0,professional_accounting,Which of the following items is not subject to...,False,Step 1: Understand what intraperiod tax alloca...,Step 1: Understand what intraperiod tax alloca...,D,B,B,B,b,B
1,professional_accounting,Pine Co. purchased land for $450000 as a facto...,False,Step 1: Understand that the cost to be capital...,Step 1: Understand that the cost to be capital...,C,D,D,A,a,D
2,professional_accounting,Spark Co. buys cordless phones for $125 each a...,False,Step 1: Calculate the profit per unit by subtr...,Step 1: Calculate the profit per unit by subtr...,D,"The calculation process was flawed, leading to...","The calculation process was flawed, leading to...",D,d,"The calculation process was flawed, leading to..."
3,professional_accounting,The standard deviations of Stocks A and B are ...,False,Step 1: Understand that the standard deviation...,Step 1: Understand that the standard deviation...,A,None of the options match the calculated value...,None of the options match the calculated value...,None of the options match the calculated value...,a,None of the options match the calculated value...
4,professional_accounting,A shoe retailer allows customers to return sho...,False,Step 1: Understand the problem. The company ne...,Step 1: Understand the problem. The company ne...,B,C,C,B,b,C
...,...,...,...,...,...,...,...,...,...,...,...
2469,disambiguation_qa,"In the following sentences, explain the antece...",True,NaN,NaN,C,A,A,A,A,A
2470,disambiguation_qa,"In the following sentences, explain the antece...",True,NaN,NaN,B,B,B,B,B,B
2471,disambiguation_qa,"In the following sentences, explain the antece...",True,NaN,NaN,B,B,B,B,B,B
2472,disambiguation_qa,"In the following sentences, explain the antece...",True,NaN,NaN,C,C,C,C,C,C
2473,disambiguation_qa,"In the following sentences, explain the antece...",True,NaN,NaN,A,A,A,A,A,A

In [56]:
df_test = pd.read_csv('final_result_claude3.csv')
df_test

,Category,Question,Correct_Answer,Output_Answer,Consistency,Cot,Cot_Answer,Smv_Answer,Cot_random,Cot_random_answer,...,raw_cot,corrected_cot,Model,Name,cot1,cot2,cot3,answer1,answer2,answer3
0,professional_accounting,Which of the following items is not subject to...,D,B,False,Step 1: Understand what intraperiod tax alloca...,D,B,Step 1: Understand what intraperiod tax alloca...,B,...,Step 1: Understand what intraperiod tax alloca...,Step 1: To answer which item is not subject to...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,professional_accounting,Pine Co. purchased land for $450000 as a facto...,C,A,False,Step 1: Understand that the cost to be capital...,A,D,step 1: Understand that the cost of the comple...,D,...,Step 1: Understand that the cost to be capital...,Step 1: Understand that the cost to be capital...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,professional_accounting,Spark Co. buys cordless phones for $125 each a...,D,D,False,Step 1: Calculate the profit per unit by subtr...,"The calculation process was flawed, leading to...","The calculation process was flawed, leading to...","step 1: Calculate the desired profit margin, w...","The calculation process was flawed, leading to...",...,Step 1: Calculate the profit per unit by subtr...,Step 4: To summarize the thought process:\n\nS...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,professional_accounting,The standard deviations of Stocks A and B are ...,A,None of the options match the calculated value...,False,Step 1: Understand that the standard deviation...,None of the options match the calculated value...,None of the options match the calculated value...,Step 1: Understand that the standard deviation...,None of the options match the calculated value...,...,Step 1: Understand that the standard deviation...,Step 1: Understand that the standard deviation...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,professional_accounting,A shoe retailer allows customers to return sho...,B,B,False,Step 1: Understand the problem. The company ne...,C,C,Step 1: Understand the problem. The company ne...,C,...,Step 1: Understand the problem. The company ne...,Step 1: Understand the problem. The company ne...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2474,disambiguation_qa,"In the following sentences, explain the antece...",B,B,True,NaN,NaN,B,NaN,B,...,NaN,NaN,claude-3-haiku-20240307,BigBench_hard,"Step 1: In the given sentence, the pronoun 'hi...",Step 1: The sentence is 'After meeting with th...,Step 1: Identify the pronoun in the sentence. ...,B,B,B
2475,disambiguation_qa,"In the following sentences, explain the antece...",B,B,True,NaN,NaN,B,NaN,B,...,NaN,NaN,claude-3-haiku-20240307,BigBench_hard,Step 1: Identify the pronouns in the sentence....,Step 1: Identify the pronouns in the given sen...,Step 1: The pronoun 'him' in the given sentenc...,B,B,B
2476,disambiguation_qa,"In the following sentences, explain the antece...",C,C,True,NaN,NaN,C,NaN,C,...,NaN,NaN,claude-3-haiku-20240307,BigBench_hard,Step 1: Identify the pronoun in the sentence. ...,Step 1: Identify the pronoun in the sentence. ...,Step 1: The given sentence is 'The developer m...,C,C,C
2477,disambiguation_qa,"In the following sentences, explain the antece...",A,C,True,NaN,NaN,C,NaN,C,...,NaN,NaN,claude-3-haiku-20240307,BigBench_hard,Step 1: The sentence is 'The educator was meet...,Step 1: The sentence states 'their grading pol...,Step 1: The sentence mentions 'the educator' a...,C,C,C
2478,disambiguation_qa,"In the following sentences, explain the antece...",B,C,True,NaN,NaN,C,NaN,C,...,NaN,NaN,claude-3-haiku-20240307,BigBench_hard,"Step 1: In the given sentence, the pronoun 'th...",Step 1: The sentence is 'The designer collabor...,Step 1: The pronoun 'them' in the sentence 'Th...,C,C,C

In [64]:
df_test.fillna('error',inplace=True)
df_test['Model'] = 'claude-3-sonnet'
df_test.drop(columns='Name',inplace=True)

KeyError: "['Name'] not found in axis"

In [66]:
for row_index in range(len(df_test)):
    row = df_test.iloc[row_indx]
    if row['cot1'] == 'error':
        row['cot1'] = row['raw_cot']
    df_test.iloc[row_indx] = row
df_test

C:\Users\77388\AppData\Local\Temp\ipykernel_11540\1186901136.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['cot1'] = row['raw_cot']

,Category,Question,Correct_Answer,Output_Answer,Consistency,Cot,Cot_Answer,Smv_Answer,Cot_random,Cot_random_answer,...,Hallu Seq,raw_cot,corrected_cot,Model,cot1,cot2,cot3,answer1,answer2,answer3
0,professional_accounting,Which of the following items is not subject to...,D,B,False,Step 1: Understand what intraperiod tax alloca...,D,B,Step 1: Understand what intraperiod tax alloca...,B,...,"['NO', 'NO', 'NO', 'NO', 'NO', 'NO']",Step 1: Understand what intraperiod tax alloca...,Step 1: To answer which item is not subject to...,claude-3-sonnet,error,error,error,error,error,error
1,professional_accounting,Pine Co. purchased land for $450000 as a facto...,C,A,False,Step 1: Understand that the cost to be capital...,A,D,step 1: Understand that the cost of the comple...,D,...,"['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO']",Step 1: Understand that the cost to be capital...,Step 1: Understand that the cost to be capital...,claude-3-sonnet,error,error,error,error,error,error
2,professional_accounting,Spark Co. buys cordless phones for $125 each a...,D,D,False,Step 1: Calculate the profit per unit by subtr...,"The calculation process was flawed, leading to...","The calculation process was flawed, leading to...","step 1: Calculate the desired profit margin, w...","The calculation process was flawed, leading to...",...,"['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO']",Step 1: Calculate the profit per unit by subtr...,Step 4: To summarize the thought process:\n\nS...,claude-3-sonnet,error,error,error,error,error,error
3,professional_accounting,The standard deviations of Stocks A and B are ...,A,None of the options match the calculated value...,False,Step 1: Understand that the standard deviation...,None of the options match the calculated value...,None of the options match the calculated value...,Step 1: Understand that the standard deviation...,None of the options match the calculated value...,...,"['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO']",Step 1: Understand that the standard deviation...,Step 1: Understand that the standard deviation...,claude-3-sonnet,error,error,error,error,error,error
4,professional_accounting,A shoe retailer allows customers to return sho...,B,B,False,Step 1: Understand the problem. The company ne...,C,C,Step 1: Understand the problem. The company ne...,C,...,"['NO', 'NO', 'NO', 'NO', 'NO']",Step 1: Understand the problem. The company ne...,Step 1: Understand the problem. The company ne...,claude-3-sonnet,error,error,error,error,error,error
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2474,disambiguation_qa,"In the following sentences, explain the antece...",B,B,True,error,error,B,error,B,...,error,error,error,claude-3-sonnet,"Step 1: In the given sentence, the pronoun 'hi...",Step 1: The sentence is 'After meeting with th...,Step 1: Identify the pronoun in the sentence. ...,B,B,B
2475,disambiguation_qa,"In the following sentences, explain the antece...",B,B,True,error,error,B,error,B,...,error,error,error,claude-3-sonnet,Step 1: Identify the pronouns in the sentence....,Step 1: Identify the pronouns in the given sen...,Step 1: The pronoun 'him' in the given sentenc...,B,B,B
2476,disambiguation_qa,"In the following sentences, explain the antece...",C,C,True,error,error,C,error,C,...,error,error,error,claude-3-sonnet,Step 1: Identify the pronoun in the sentence. ...,Step 1: Identify the pronoun in the sentence. ...,Step 1: The given sentence is 'The developer m...,C,C,C
2477,disambiguation_qa,"In the following sentences, explain the antece...",A,C,True,error,error,C,error,C,...,error,error,error,claude-3-sonnet,Step 1: The sentence is 'The educator was meet...,Step 1: The sentence states 'their grading pol...,Step 1: The sentence mentions 'the educator' a...,C,C,C
2478,disambiguation_qa,"In the following sentences, explain the antece...",B,C,True,error,error,C,error,C,...,error,error,error,claude-3-sonnet,"Step 1: In the given sentence, the pronoun 'th...",Step 1: The sentence is 'The designer collabor...,Step 1: The pronoun 'them' in the sentence 'Th...,C,C,C